# used in menu items and in admin navigation
class Icon
  DASHBOARD = 'fas fa-chart-line'

  COMMUNICATION_EXTRANET = 'fas fa-project-diagram'
  COMMUNICATION_WEBSITE = 'fas fa-sitemap'
  COMMUNICATION_WEBSITE_HOME = 'fas fa-home'
  COMMUNICATION_WEBSITE_POST = 'fas fa-newspaper'
  COMMUNICATION_WEBSITE_PAGE = 'fas fa-file'
  COMMUNICATION_WEBSITE_PAGES = 'fas fa-sitemap'
  COMMUNICATION_WEBSITE_MENUS = 'fas fa-bars'
  COMMUNICATION_WEBSITE_ANALYTICS = 'fas fa-chart-pie'
  COMMUNICATION_WEBSITE_PREVIEW_MOBILE = 'fas fa-mobile-alt'
  COMMUNICATION_WEBSITE_PREVIEW_TABLET = 'fas fa-tablet-alt'
  COMMUNICATION_WEBSITE_PREVIEW_DESKTOP = 'fas fa-laptop'
  COMMUNICATION_WEBSITE_MENU_BLANK = 'fas fa-font'
  COMMUNICATION_WEBSITE_MENU_URL = 'fas fa-globe'
  COMMUNICATION_NEWSLETTERS = 'fas fa-envelope'

  EDUCATION_DIPLOMA = 'fas fa-graduation-cap'
  EDUCATION_PROGRAM = 'fas fa-chalkboard-teacher'
  EDUCATION_SCHOOL = 'fas fa-university'
  EDUCATION_TEACHER = 'fas fa-user-graduate'
  EDUCATION_RESOURCES = 'fas fa-laptop'
  EDUCATION_FEEDBACKS = 'fas fa-comments'

  RESEARCH_JOURNAL = 'fas fa-newspaper'
  RESEARCH_LABORATORY = 'fas fa-flask'
  RESEARCH_RESEARCHER = 'fas fa-microscope'
  RESEARCH_THESE = 'fas fa-scroll'
  RESEARCH_WATCH = 'fas fa-eye'

  ADMINISTRATION_CAMPUS = 'fas fa-map-marker-alt'
  ADMINISTRATION_ADMISSIONS = 'fas fa-door-open'
  ADMINISTRATION_INTERNSHIPS = 'fas fa-hands-helping'
  ADMINISTRATION_STATISTICS = 'fas fa-chart-bar'
  ADMINISTRATION_QUALITY = 'fas fa-tasks'

  UNIVERSITY_ORGANIZATION = 'fas fa-building'
  UNIVERSITY_PERSON = 'fas fa-users'
  UNIVERSITY_PERSON_ADMINISTRATORS = 'fas fa-users-cog'
  UNIVERSITY_PERSON_ALUMNUS = 'fas fa-user-graduate'

  OSUNY_USER = 'fas fa-user'
  
  ADD = 'fas fa-plus'
  ARROW_RIGHT = 'fas fa-arrow-right'
  A11Y = 'fas fa-universal-access'
  CHECK_OK = 'fas fa-check'
  CHECK_KO = 'fas fa-times'
  FOLDER_CLOSED = 'far fa-folder'
  FOLDER_OPENED = 'far fa-folder-open'
  FOLDER_CLOSED_FULL = 'fas fa-folder'
  FOLDER_OPENED_FULL = 'fas fa-folder-open'
  DRAG = 'fas fa-bars'
  DELETE = 'fas fa-times'
  FILE = 'fas fa-file'
  FILTERS = 'fas fa-filter'
  MOVE = 'fas fa-arrows-alt'
  SETTINGS = 'fas fa-gear'
  SORT = 'fas fa-sort'
  WARNING = 'fas fa-exclamation-circle'
end
