# used in menu items and in admin navigation
class Icon
  DASHBOARD = 'chart-line'

  COMMUNICATION_EXTRANET = 'project-diagram'
  COMMUNICATION_WEBSITE = 'sitemap'
  COMMUNICATION_WEBSITE_HOME = 'home'
  COMMUNICATION_WEBSITE_POST = 'newspaper'
  COMMUNICATION_WEBSITE_PAGE = 'file'
  COMMUNICATION_WEBSITE_PAGES = 'sitemap'
  COMMUNICATION_WEBSITE_MENUS = 'bars'
  COMMUNICATION_WEBSITE_ANALYTICS = 'chart-pie'
  COMMUNICATION_WEBSITE_PREVIEW_MOBILE = 'mobile-alt'
  COMMUNICATION_WEBSITE_PREVIEW_TABLET = 'tablet-alt'
  COMMUNICATION_WEBSITE_PREVIEW_DESKTOP = 'laptop'

  EDUCATION_DIPLOMA = 'graduation-cap'
  EDUCATION_PROGRAM = 'chalkboard-teacher'
  EDUCATION_SCHOOL = 'university'
  EDUCATION_TEACHER = 'user-graduate'

  RESEARCH_JOURNAL = 'newspaper'
  RESEARCH_LABORATORY = 'flask'
  RESEARCH_PUBLICATION = 'book'
  RESEARCH_RESEARCHER = 'microscope'
  RESEARCH_THESE = 'scroll'

  UNIVERSITY_ORGANIZATION = 'building'
  UNIVERSITY_PERSON = 'users'
  UNIVERSITY_PERSON_ADMINISTRATORS = 'users-cog'
  UNIVERSITY_PERSON_ALUMNUS = 'user-graduate'
end
