config_version = "0"

exclude_patterns = [
  "node_modules/**",
  "vendor/**",
  "db/**",
  "config/**",
  "docs/**",
  "spec/**",
  "test/**"
]

test_patterns = [
  "spec/**",
  "test/**"
]

[[source]]
name = "default"
default = true

[smells]
mode = "comment"
